# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 06:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_bt_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='bt_test',
            name='favorite',
            field=models.ManyToManyField(help_text='收藏该种子的用户', related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
