# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bt_test_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bt_test',
            options={},
        ),
        migrations.RemoveField(
            model_name='bt_test',
            name='user',
        ),
    ]
